# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

from snakemake.utils import min_version

min_version("6.5.2")


container: "docker://continuumio/miniconda3"


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/cnvkit.smk"
include: "rules/oncoprint.smk"


rule cnvkit:
    input:
        "results/cnvkit/gistic.input.seg",
        "results/oncoprint/tumor_supressor_deletions_only.pdf",
        "results/oncoprint/oncogene_amplifications_only.pdf",
        "results/oncoprint/oncogene_vgp.pdf",
