# path to the sample sheet 
samples: config/samples.tsv

# download link for the OncoKB, please ensure you comply with the license and
# cite OncoKB correctly, see: https://www.oncokb.org/apiAccess
onco_kb: "https://www.oncokb.org/api/v1/utils/cancerGeneList.txt"


# how to install GISTIC2: https://software.broadinstitute.org/cancer/cga/gistic
# or here https://github.com/ShixiangWang/install_GISTIC
# consider to use unset DISPLAY option...

alias_prefixes:
  tumor: "tumor"
  normal: "normal"
  panel_of_normals: "panel_of_normals"

# One option here is an actual path to a reference fasta file (like
# "resources/my_genome.fasta"). But you can also ensure that this key gets set
# in an encompassing workflow that loads this workflow as a module, for example
# by assigning the path of the reference creating by another imported module
# that was used for creating the BAM files (mapping). Just assign it to:
# config["ref"] = "path/to/ref.fasta"
ref: "resources/my_genome.fasta"

cnvkit:
  batch: ""
  access_param: "-s 10000"
  call_param: ""
  # This needs to be an event, configured in the dna-seq-varlociraptor
  # workflow, that calls all variants present in the tumor and normal sample.
  # Usually, a catch-all event gathering all the events specified in the
  # scenario.yaml file should be used.
  joint_event: "present"


oncoprint:
  title: "Oncoprint Title"