# copy and set up this workflow: https://github.com/snakemake-workflows/dna-seq-varlociraptor
#subworkflow:
#    workdir: "path/to/workdir"
#    snakefile: "path/to/workdir/workflow/Snakefile"
#    configfile: "path/to/workdir/config/config.yaml"


# path to the sample sheet 
samples: config/samples.tsv
cnv_targets: config/cnv_targets.tsv

# path to bam directory
bam_directory: "INPUT/"

# path to genome reference
ref_fasta: "INPUT/ref_genome.fasta"

aliases:
    tumor: "tumor"
    normal: "normal"

CNVkit:
    mode: "batch" # batch, tumor_only, pool



# path to the OncoKB (it can be downloaded from https://www.oncokb.org/cancerGenes) 
OncoKB: "INPUT/OncoKB.tsv"


# how to install GISTIC2: https://software.broadinstitute.org/cancer/cga/gistic
# or here https://github.com/ShixiangWang/install_GISTIC
# consider to use unset DISPLAY option...

params:
    cnvkit:
        access_param: "-s 10000"
        run_cnvkit: ""
        call_param: ""


oncoprint:
    title: "Oncoprint Title"